version: '2'
services:
  app:
    image: rmts/app:7.0
    volumes:
      - ./:/var/www/html:cached
      - ~/.ssh:/root/.ssh:cached
      - /tmp
      # to enter via ssh (remote testing)
      # ports:
      #   - "20201:22"
    environment:
      - "VIRTUAL_HOST=CUSTOMER.lvh.me"
      - "VIRTUAL_PORT=80"
    networks:
      - CUSTOMERnet
      - nginx-proxy

  database:
    image: rmts/database:10.1
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
#    ports:
#      - "33062:3306"
    networks:
      - CUSTOMERnet

  database-testing:
    image: rmts/database:10.1
    environment:
      - "MYSQL_DATABASE=testing"
    networks:
      - CUSTOMERnet

  redis:
    image: redis:4-alpine
    networks:
      - CUSTOMERnet

  webpack:
    image: rmts/webpack:8
    volumes:
      - ./:/home/app:cached
      - /home/app/node_modules
    networks:
      - CUSTOMERnet

  elasticsearch:
    image: elasticsearch:2.4.5
    networks:
      - CUSTOMERnet

  kibana:
    image: kibana:4.6.6
    environment:
      - "VIRTUAL_HOST=kibana.CUSTOMER.lvh.me"
      - "VIRTUAL_PORT=5601"
    networks:
      - CUSTOMERnet
      - nginx-proxy

networks:
  CUSTOMERnet:
    driver: bridge
  nginx-proxy:
    external:
      name: ngnixproxy_default